TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.0
  max_vel_theta: 2.0
  min_in_place_vel_theta: 0.0

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  yaw_goal_tolerance: 6.28 # 2*pi, ignore orientation
  xy_goal_tolerance: 0.5