global_frame: /map
robot_base_frame: base_link
update_frequency: 5.0
static_map: true
rolling_window: false
transform_tolerance: 2.0
obstacle_range: 50
raytrace_range: 3.0
inflation_radius: 2.0
footprint: [[-0.3, -0.6], [-0.3, 0.6], [1.8, 0.5], [1.8, -0.5]]
plugins:
    - {name: static_map,     type: "costmap_2d::StaticLayer"}
    #- {name: inflation_map,  type: "costmap_2d::InflationLayer"}

