obstacle_range: 50
raytrace_range: 3.0
inflation_radius: 0.5
transform_tolerance: 2.0
footprint: [[-0.3, -0.6], [-0.3, 0.6], [1.8, 0.5], [1.8, -0.5]]
obstacle_layer:
  observation_sources: laser_scan_sensor

  laser_scan_sensor: {
    sensor_frame: laser,
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true  
  }

static_layer:
  lethal_cost_threshold: 50
