local_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 2.0
  transform_tolerance: 2.0
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05